# Recipients for nodes/secrets/*. Janus does not get the k3s token.
keys:
  - &cluster age10r8tatzk4q8g9q23s4z336j3u86k74ytmt6ky07mk0av9luux9rqnwns99
  - &pingu age1de4g7dmplmfrymqy0843hlf4yg8cg8j088prektl8emed2yy6c7qcru5gr
  - &remorse age1c26sktwy7dqwjzwlfs4zmaexngpld2py2qpqp6pzm3v6f8thtfes7nvu93
creation_rules:
  - path_regex: cluster\.yaml$
    key_groups:
      - age:
          - *cluster
          - *pingu
          - *remorse
