apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Ioow3fs=,iv:DjmF6SPiEJxmJsDM7pEGT8pXEw9XW5iNkOPBW3HlTbk=,tag:D6aA6tJKcV1s0VmJcd9pqQ==,type:str]
    admin-password: ENC[AES256_GCM,data:BC61P9xnVX9VU57d7ifaiK9DywNly5KC34lDk9R7PI4=,iv:DswQ5SITWYo/EY/PDpd0hSc+uLvlTiPmQgz8DifEE9g=,tag:kSezfnDxS/xCdrwJZr4dYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV0JOR0R2Y0phTmZHZnBV
            NStaQ1kvUU9QcnovQXNIcitkWEV0ZkYxVzNvCld5d1dHeGhSazhWcUF2cmJsQm9k
            SjN0ajdYTjFpSDlkTTNtOCtsUW9rdlkKLS0tIFZmalN6OUtGUGRQdzRPT2dYbU9S
            WXRDNngwNDZuRjZaalc3eU9rbVVhOUkK4iV28IEGSGUb2q7kAc0gB4RidO3Q/3TS
            mvZyxVkONHHH51oonZnYRQ1it20hiSWc7ubidTp35CPYElEbuPx3lQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10r8tatzk4q8g9q23s4z336j3u86k74ytmt6ky07mk0av9luux9rqnwns99
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMHdDSzB3aDRSNmlUZEFO
            QnFObUJzL0ZpdlJ0RFZrNzVXbGVMNWpLVlQwCnl4U1BvaW11TjNUbGdTWU0zTWtZ
            Vkg5SFJ2S0RnNzFpTHdSMzV3MGFLZ00KLS0tIEU1UzFjOUVOeFNlUWtNSGtLT3NY
            dTdETUVlY2g3enRvVnl2VFNQMW1mY00K1n0K033BXA+oezflUwmmFT+N5eXsgHEU
            3c5oQnBhajHMjGn+/5+qG3/bm21FvL+D6atO0Halq8LffOd1FXl4PQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1de4g7dmplmfrymqy0843hlf4yg8cg8j088prektl8emed2yy6c7qcru5gr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNER3bWc4cjZPMHZiU2Mr
            WTFCeG5HUHdHY20vSzMvMmtuRzhuR2trNnlNCk5TOGczekN0YjlnRTBwY2NwSjFK
            bzZyQkZlUVo5QjZzcXRLZnNDZ3BrVHMKLS0tIGxVeUU2N2hMQWRVZjlpcHpUMS9n
            SlpvNzdjV0puZnVwVVo2T095aFVENmMKfJeqlSOFOhUPi0kQW5D3D0zqjFF1ve04
            6IkR9g0mUGGteqx7zA5PQKMkbssb2+f1V5Vf2ZfjFmx3Gocf7SOVUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c26sktwy7dqwjzwlfs4zmaexngpld2py2qpqp6pzm3v6f8thtfes7nvu93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T16:52:15Z"
    mac: ENC[AES256_GCM,data:n8s6dTgV+z5wHakDWuBELtteF0dT0L97Qut6wQg6g2ClnHwKOE0WKSJnGlZLcrpHV2JT/75r5iYnEU7OUwD0xzfUELPWiuy80+u91Z+II3DSMTK2iB6lxe3qU5yRIsaXl2lCEqRgUrSFqsGaJ4HK1a0U6far1jBN0sx0Tns6380=,iv:7H847wIdFyympfV5pFlvk6DDwMCPdJUYzwjdsS146sc=,tag:TToMRLLcesZ7uioohr2LIg==,type:str]
    version: 3.13.3
