apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Ioow3fs=,iv:DjmF6SPiEJxmJsDM7pEGT8pXEw9XW5iNkOPBW3HlTbk=,tag:D6aA6tJKcV1s0VmJcd9pqQ==,type:str]
    admin-password: ENC[AES256_GCM,data:BC61P9xnVX9VU57d7ifaiK9DywNly5KC34lDk9R7PI4=,iv:DswQ5SITWYo/EY/PDpd0hSc+uLvlTiPmQgz8DifEE9g=,tag:kSezfnDxS/xCdrwJZr4dYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQmZOUUt3RFh2OE9mblJM
            NVd4NkNWNGF5NmFyVXlZNkRjZk5YeThjV1JnCnhZWXpWcXN2RzA0dFlyelJtcXc3
            bzc0dXNobGlsbFZxbHFrOVNGdk1YazgKLS0tIDlqZXhSS0JhSDI0Q0pFazBwL0w0
            YjE2RW16K3Zqcnh5TU1PRmJGSmJJL28KB3jHg0rFZIUCzhCjuWKsCpMpqShC9YgZ
            KulZPyx9bnMzXgsaK9audvwRTUWRpo3eZOISLShFkWJbnfDsXCSCOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10r8tatzk4q8g9q23s4z336j3u86k74ytmt6ky07mk0av9luux9rqnwns99
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVXNha09nOVJQQ0IwblRE
            TERlbXZ1U1ZJSTA3djM5NDJjNmFYUEdxSnhVCmxmdFcxcEk3ZnZ2czhSMldMR1Fk
            Wk1KOGxIRzdUaTNRQUtCaTlRNzlZTHcKLS0tIG81M0Y5My84WTVBMXpLbVJWSU51
            OEpram9iM3l5RjZHK1JpTDMxZTRrd0EKG+geHu27sFrY3zZlgTE9ZhmLyMuKVhPG
            uPozTFmUKZXZFTLyFE5d6OfyTozhFmC9NROEY0E9XlUhv+0Wok7QLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r203lu8zp7twadza7cqaxjykfa53vtsk04cljpnt8rgknml9qf0qh6j4qr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMWZMWFY5ejRqbE1Rdjhr
            d3JLVFc1V1pUNHJqWGNtKyt5V1lkNlhjQkNJCk43VnZLMmE5djZPNkQxSXdLVFNP
            N09JaFlpRm5sQVNxVnlSbWJBYUF4d1kKLS0tIDRYTC9PZVpHYytubWJPbnB5Yi9M
            WGJtb2lxbmMxOWJ0T2t3M0pZTFRleGcKDvvAFBIcYCbEZaMU1syc+UB8OD48VQ6l
            3z6/xZl7qjOSFuWwy5KR+5stL7PFhL522scsyGsU1bx310sUZ2ss1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l0lcgknsxv8jkhc89vr6g7pj6cp9rtqkqejjpnuhwed6c52kqphsrwzd7d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T16:52:15Z"
    mac: ENC[AES256_GCM,data:n8s6dTgV+z5wHakDWuBELtteF0dT0L97Qut6wQg6g2ClnHwKOE0WKSJnGlZLcrpHV2JT/75r5iYnEU7OUwD0xzfUELPWiuy80+u91Z+II3DSMTK2iB6lxe3qU5yRIsaXl2lCEqRgUrSFqsGaJ4HK1a0U6far1jBN0sx0Tns6380=,iv:7H847wIdFyympfV5pFlvk6DDwMCPdJUYzwjdsS146sc=,tag:TToMRLLcesZ7uioohr2LIg==,type:str]
    version: 3.13.3
