apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vlan30
  namespace: metallb-system
spec:
  addresses:
    - 10.10.30.100-10.10.30.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vlan30
  namespace: metallb-system
spec:
  ipAddressPools:
    - vlan30
