# age recipients filled after keygen — see docs/reference/secrets-sops-vs-agenix.md
keys:
  - &janus age1mg3k4jmgm5gfpe0uce5g4e899dp5zycl98g9qys0p84ggn0zzg7qyaxh63
  - &pingu age1r203lu8zp7twadza7cqaxjykfa53vtsk04cljpnt8rgknml9qf0qh6j4qr
  - &remorse age1l0lcgknsxv8jkhc89vr6g7pj6cp9rtqkqejjpnuhwed6c52kqphsrwzd7d
creation_rules:
  - path_regex: router\.yaml$
    key_groups:
      - age:
          - *janus
          - *pingu
          - *remorse
  - path_regex: cluster\.yaml$
    key_groups:
      - age:
          - *janus
          - *pingu
          - *remorse
